### PR TITLE
Bugfix/proj 856

### PR DESCRIPTION
**Pull request by hbandi2**
PROJ-856 Vertical scroll issue in touch devices. Issue occurring due to links.Timeline.preventDefault(event); statement in touchstart, touchmove, touchend, mousedown and mousemove event handlers in timeline.js, which is preventing default actions.

### CODE REVIEW

**Comment by nrw** [comment]
i see a lot of formatting changes. in this 4600 line commit, where did you make changes to the logic?

**Comment by hbandi2** [comment]
Please go through the comment...i just commented links.Timeline.preventDefault(event); line in touchstart, touchmove, touchend, mousedown and mousemove event handlers

**Comment by nrw** [comment]
i see those commented lines now. can we do this without the massive reformat? for a 5 line change, i think seeing the actual logical change of this commit is more valuable. maybe do the reformat on it's own commit?

**Comment by hbandi2** [comment]
i guess it is one time change and we own this code, its better to be formatted as per our settings.
What do you say?

**Comment by nrw** [comment]
if no one else has a problem with it, i will certainly yield on this.

**Review by nrw — APPROVED** [review]

**Pull request closed without merging**
